// Mocks generated by Mockito 5.1.0 from annotations
// in date_trivia/test/features/date_trivia/domain/usecases/get_concrete_date_trivia_test.dart.
// Do not manually edit this file.

import 'package:date_trivia/features/date_trivia/domain/repositories/date_trivia_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DateTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTriviaRepository extends _i1.Mock
    implements _i2.DateTriviaRepository {
  MockDateTriviaRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DateTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTriviaRepositoryForTest extends _i1.Mock
    implements _i2.DateTriviaRepository {}
